### ISSUE TITLE
how to find the current_user voted for the post?

### ISSUE THREAD

**Issue by Sri-K** [ryanto/acts_as_votable#108]
I have the following code in my view:

if current_user.voted_for? post => gives me undefined method voted_for?

How can I know the current user is voted for the post?

Thanks

**Comment by TylerTaylor** [comment]
What if I do have ```acts_as_voter``` in the user model, and I'm still getting that error? Seems like everything I'm trying to do to see if a user has liked something, returns that error. Likes, voted_up_on, liked_by, etc. Thanks for any help

**Comment by halilim** [comment]
@TylerTaylor is `current_user` present and an instance of `User`? It's hard to make an educated guess without more info/code but you can try the console to see if the problem is in the model or the controller etc.: `User.first.voted_up_on?(Something.first)` (`Something` must have `acts_as_votable` in it).

**Comment by dizo1** [comment]
Hallo ? am trying to implement voting restricted to once per 24 hours per user and can't seem to find a way any help?

**Comment by epergo** [comment]
Hi! Closing because OP has been inactive since December 2015.

@dizo1 Feel free to create a new Issue if you feel you need to.

**Comment by dizo1** [comment]
Need some help with that
