### ISSUE TITLE
ActiveAdmin: undefined method `vote_by' for nil:NilClass

### ISSUE THREAD

**Issue by tnld** [ryanto/acts_as_votable#110]
I always get this error message when I want to view a User via the ActiveAdmin interface. The User model doesn't act as votable, so I have no idea why he's even looking for the 'vote_by' method.

My User model:

```
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :invitable

  validates_presence_of :username

  has_and_belongs_to_many :categories

  acts_as_voter
  acts_as_reader

  extend FriendlyId
  friendly_id :username, use: :slugged
end
```

Full error message:

```
ActionView::Template::Error (undefined method `vote_by' for nil:NilClass):
    1: insert_tag renderer_for(:show)
acts_as_votable (0.10.0) lib/acts_as_votable/voter.rb:39:in `vote'
acts_as_votable (0.10.0) lib/acts_as_votable/voter.rb:43:in `vote_up_for'
/home/user/.rvm/gems/ruby-2.1.4/bundler/gems/activeadmin-8c87611980fa/lib/active_admin/views/components/attributes_table.rb:92:in `public_send'
/home/user/.rvm/gems/ruby-2.1.4/bundler/gems/activeadmin-8c87611980fa/lib/active_admin/views/components/attributes_table.rb:92:in `find_attr_value'
/home/user/.rvm/gems/ruby-2.1.4/bundler/gems/activeadmin-8c87611980fa/lib/active_admin/views/components/attributes_table.rb:82:in `content_for'
/home/user/.rvm/gems/ruby-2.1.4/bundler/gems/activeadmin-8c87611980fa/lib/active_admin/views/components/attributes_table.rb:39:in `block (3 levels) in row'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:14:in `td'
```

Any idea what might cause this?

**Comment by glampr** [comment]
Had a similar issue which was resolved when I explicitly defined which fields I want to view in Active Admin (in all index/show/form pages)

**Comment by glampr** [comment]
Just figured out that what is causing this is when your model has a database column with the same name as one of the alias the gem makes for its vote methods:

For example in https://github.com/ryanto/acts_as_votable/blob/master/lib/acts_as_votable/voter.rb

```
      # allow user to define these
      aliases = {
        :vote_up_for    => [:likes, :upvotes, :up_votes],
        :vote_down_for  => [:dislikes, :downvotes, :down_votes],
        :unvote_for     => [:unlike, :undislike],
        :voted_on?      => [:voted_for?],
        :voted_up_on?   => [:voted_up_for?, :liked?],
        :voted_down_on? => [:voted_down_for?, :disliked?],
        :voted_as_when_voting_on => [:voted_as_when_voted_on, :voted_as_when_voting_for, :voted_as_when_voted_for],
        :find_up_voted_items   => [:find_liked_items],
        :find_down_voted_items => [:find_disliked_items]
      }
```

If you have a column with the same name as the values of the hash above the this exception is raised because rails checks to see if the model is changed (by running the ```changes``` method) which in turn will run some "vote" method.

i.e. I had a ```likes``` column in my user model and when I renamed it the problem was gone.

**Comment by stevewebdevfl** [comment]
@glampr, re your entry of Jan 17:  Thank you for the post!  Would you please clarify something?  That is, when you refer to columns "with the same name as the values of the hash above", does this refer to only my database columns that existed before the gem was installed?  The columns 'up_votes' & 'down_votes' were added to both my acts_as_votable and acts_as_voter models, and it would be strange if the columns added by the gem were the reason for the undefined method error.  None of the pre-gem database columns match anything in the voter.rb segment shown in your post. I thank you in advance for your help!

**Comment by glampr** [comment]
Hi @stevewebdevfl , not sure what you mean by 'columns added by the gem'.
It's been a while but from what I remember, the issue is cause when there exists a column in your model with one of the names above: e.g. 'likes', 'downvotes'.
When rails looks for changes it will query these methods, but will actually run the aliased "vote" method (probably without the arguments it needs) which will cause the error. Hope this helps.

**Comment by epergo** [comment]
Hi @stevewebdevfl , did you resolve this issue? If no, could you please provide any sort of example application where we can replicate the error?

Thank you!
