### ISSUE TITLE
Acts_as_votable with polymorphic associations

### ISSUE THREAD

**Issue by ddonche** [ryanto/acts_as_votable#143]
I'm trying to get acts_as_votable to work on two resource types, blogs and articles. But then I have comments that share a relationship with both blogs and articles. I can get the voting to work on the blogs and articles, but not the comments. I really like the answer provided in[ another issue](https://github.com/ryanto/acts_as_votable/issues/105) on the gem here, but how can I change post to a variable so that it will work with either blogs or articles? The below code was a solution from the link. 

```
# routes.rb
...
resources :posts do
  resources :votes, only: [:create]
  resources :comments do
    resources :votes, only: [:create]
  end
end
```
A separate votes controller. As you can see, it's easy to do if you have only one resource the comment belongs to. 
```
...
post = Post.find(params[:post_id])
comment = post.comments.find(params[:comment_id]) if params[:comment_id]

obj = comment || post

if current_user.liked? obj
  obj.disliked_by current_user
else
  obj.liked_by current_user
end
...
```
```
And the view:
# view: to vote on a post
= link_to 'Vote', post_votes_path(@post), remote: true, method: :post

# view: to vote on a comment (of a post)
= link_to 'Vote', post_comment_votes_path(@post, comment), remote: true, method: :post
```

**Comment by danfrenette** [comment]
Not sure if this is still valuable to you four and a half months down the road, but I was able to achieve an app that accomplishes this pretty easily. The main difference is I used a custom votes route instead of using resources. So instead of:

```...
resources :posts do
  resources :votes, only: [:create]
  resources :comments do
    resources :votes, only: [:create]
  end
end

Try:

```
# routes.rb
...
resources :posts do
  post :votes
  resources :comments do
    post :votes
  end
end

The end result is you being able to create two separate but much more concise actions to update and add votes to whatever you want

**Comment by ryanto** [comment]
Very cool! Thanks for the answer.
