### ISSUE TITLE
Question: Any way to like/dislike without touching updated_at column for votable object?

### ISSUE THREAD

**Issue by stevepm** [ryanto/acts_as_votable#83]
I'm trying to find a way to sort my votable object by most recently updated, because they get updated frequently, but if a user likes or dislikes the object, it gets updated as well. I'd like a way to not touch the updated column for my votable object when it gets voted on if possible.

**Comment by BrahimDahmani** [comment]
+1

**Comment by alexmc6** [comment]
I assume this is because the code wants to put cache columns on the votable object. However it should be possible to 

a) put the cache on a different table. 
or
b) not touch the votable object record if you aren't using a cache. 

I am not sure I fully understand ActiveRecord but I would call this a bug.

**Comment by epergo** [comment]
With pull request #150 now you can configure your votable model to `update_column` instead of `update_attribute` so `updated_at` column won't be updated.

Closing as it is solved.
